### PR TITLE
Add CirleCI build and test.

### PR DESCRIPTION
**Pull request by rtohid**

### CODE REVIEW

**Comment by hkaiser** [comment]
Shouldn't this already have run on CircleCI? I have added phylanx to the STE||AR-Group Circle CI tests, let's get this running properly before merging.

**Comment by rtohid** [comment]
There are a couple of builds queued on CIrcleCI, but not yet running.

**Comment by hkaiser** [comment]
@rtohid Yay, it has built everything now!

**Comment by rtohid** [comment]
@hkaiser: If you're happy with #21, I'll go ahead and close this!

**Comment by hkaiser** [comment]
This can be closed now as it is superseded by #21

**Pull request closed without merging**
