### PR TITLE
Making sure compiler can be invoked more than once

### LINKED ISSUE #543: Calling compile more than once in a row references wrong code
Calling `compile` more than once in a row using the same snippets object makes all code objects refer to the PhySL code compiled last,

### PR DESCRIPTION
**Pull request by hkaiser**
Making sure compiler can be invoked more than once in a row without causing wrong code to be referenced.

This fixes #543

### CODE REVIEW

**Comment by hkaiser** [comment]
Investigating the failing test has shown that more work is needed on this.

**Comment by stevenrbrandt** [comment]
@hkaiser do you have a sample test code that illustrates what's wrong?

**Comment by hkaiser** [comment]
@stevenrbrandt the regression test `replace_names_374` fails coincidentally thus revealing a flaw in the current PR.

**Comment by stevenrbrandt** [comment]
@hkaiser do we have an example which shows this failure?

**Pull request merged**
