### PR TITLE
Initial port of k-means algorithm to Phylanx

### PR DESCRIPTION
**Pull request by ct-clmsn**
Import k-means clustering algorithm ported from NumPy to Phylanx in Python. Implementation was ported from a BSD-licensed implementation found here:

* http://flothesof.github.io/k-means-numpy.html

### CODE REVIEW

**Comment by ct-clmsn** [comment]
numpy.newaxis is used to extend a type's dimensionality by a value of 1. additional supporting documentation:

https://stackoverflow.com/questions/29241056/how-does-numpy-newaxis-work-and-when-to-use-it
https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

**Comment by ct-clmsn** [comment]
@hkaiser i'll start putting some effort into porting codes.

@parsa thank you for helping me format of this ticket!

**Comment by ct-clmsn** [comment]
@parsa did you want me to start putting the primitives into the tracker?

**Comment by hkaiser** [comment]
> 'copy': provide a copy primitive that can do the equivalent of a "Python deep copy" operation?

In PhySL this would be equivalent to creating a variable;

    define(deep_copy_of_x, x)

not sure how this should be expressed in Python in a generic way. @stevenrbrandt ?

**Comment by ct-clmsn** [comment]
@hkaiser could a wrapper function called "copy" that is a short-hand python means of doing this operation be sufficient?

**Comment by hkaiser** [comment]
> @hkaiser could a wrapper function called "copy" that is a short-hand python means of doing this operation be sufficient?

@ct-clmsn We could try hooking into Pythons standard shallow-copy/deep-copy mechanism (https://docs.python.org/3.8/library/copy.html). Not sure if this viable, though.

**Pull request merged**
