### PR TITLE
Making sure IO primitives perform actual IO on a dedicated thread

### LINKED ISSUE #589: HPX Worker thread is doing I/O
I noticed in the TAU profiles of als_csv_instrumented that the IO thread is doing the open/close functions, but the worker thread in Phylanx is reading the ALS dataset.  This should be changed to use HPX methods that route the I/O through the I/O thread(s).

Profile of just POSIX calls:
[io_profile.pdf](https://github.com/STEllAR-GROUP/phylanx/files/2362020/io_profile.pdf)
I/O Thread Profile of POSIX calls:
[io_thread.pdf](https://github.com/STEllAR-GROUP/phylanx/files/2362023/io_thread.pdf)
Worker Thread Profile of POSIX calls:
[worker_io.pdf](https://github.com/STEllAR-GROUP/phylanx/files/2362024/worker_io.pdf)

### PR DESCRIPTION
**Pull request by hkaiser**
This fixes #589

### CODE REVIEW

**Comment by khuck** [comment]
Not sure about that specific issue, but it caused a failure in this test: tests.unit.execution_tree.generate_tree

```
[khuck@delphi phylanx-RelWithDebInfo]$ ctest -V -R tests.unit.execution_tree.generate_tree
UpdateCTestConfiguration  from :/home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/DartConfiguration.tcl
Parse Config file:/home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/DartConfiguration.tcl
Parse Config file:/home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/DartConfiguration.tcl
Test project /home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 56
    Start 56: tests.unit.execution_tree.generate_tree

56: Test command: /packages/python/3.6.4-ssl/bin/python3 "/home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/bin/phylanxrun.py" "/home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/bin/generate_tree_test" "-e" "0" "-l" "1" "-t" "1" "-v" "--"
56: Test timeout computed to be: 1500
56: 
56: {stack-trace}: 4 frames:
56: 0x7f0906514884  : hpx::detail::backtrace[abi:cxx11](unsigned long) + 0xa4 in /home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/hpx-RelWithDebInfo/lib/libhpx.so.1
56: 0x7f09065229b9  : std::__exception_ptr::exception_ptr hpx::detail::get_exception<hpx::exception>(hpx::exception const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xa9 in /home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/hpx-RelWithDebInfo/lib/libhpx.so.1
56: 0x7f0906522e88  : void hpx::detail::throw_exception<hpx::exception>(hpx::exception const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long) + 0x58 in /home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/hpx-RelWithDebInfo/lib/libhpx.so.1
56: 0x7f090656864e  : hpx::detail::throw_exception(hpx::error, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long) + 0x4e in /home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/hpx-RelWithDebInfo/lib/libhpx.so.1
56: {env}: 104 entries:
56:   ARCHDIR=x86_64
56:   BASH_ENV=/usr/share/lmod/lmod/init/bash
56:   BASH_FUNC_ml()=() {  eval $($LMOD_DIR/ml_cmd "$@")
56: }
56:   BASH_FUNC_module()=() {  eval $($LMOD_CMD bash "$@");
56:  [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
56: }
56:   BLAS_DIR=/usr/local/packages/lapack/3.7.1-gcc
56:   BLAS_ROOT=/usr/local/packages/lapack/3.7.1-gcc
56:   BOOST_DIR=/usr/local/packages/boost/1.65.0-gcc7
56:   BOOST_ROOT=/usr/local/packages/boost/1.65.0-gcc7
56:   CMAKE=/usr/local/packages/cmake/3.9.3
56:   CPLUS_INCLUDE_PATH=/packages/gcc/7.1/include:/packages/openmpi/2.0_gcc-6/include
56:   CTEST_INTERACTIVE_DEBUG_MODE=1
56:   CVSROOT=khuck@ix.cs.uoregon.edu:/research/paraducks2/cvs-src/master
56:   CVS_RSH=ssh
56:   C_INCLUDE_PATH=/packages/gcc/7.1/include:/packages/openmpi/2.0_gcc-6/include
56:   DISPLAY=localhost:12.0
56:   EDITOR=vim
56:   GAMESS=/home/users/khuck/src/gamess/gamess
56:   GCC=/packages/gcc/7.1
56:   GMP=/packages/gmp/6.1
56:   HARMONY_HOME=/usr/local/packages/activeharmony/4.6.0-gcc
56:   HDF5_LDFLAGS=-L/usr/local/packages/szip/2.1/gcc-4.9/lib -ldl -lz -lsz
56:   HDF5_ROOT=/usr/local/packages/hdf5/1.10.1-gcc-6.4
56:   HISTCONTROL=ignoredups
56:   HISTSIZE=1000
56:   HOME=/home/users/khuck
56:   HOSTNAME=delphi
56:   INFOPATH=/packages/gmp/6.1/share/info:/packages/mpfr/3.1_gmp6/share/info:/packages/mpc/1.0_gmp6/share/info:/packages/gcc/7.1/info
56:   ISL=/packages/isl/0.16.1
56:   JAVA_HOME=/home/users/khuck/build/jdk1.6.0_29
56:   LANG=en_US.UTF-8
56:   LAPACK_DIR=/usr/local/packages/lapack/3.7.1-gcc
56:   LAPACK_ROOT=/usr/local/packages/lapack/3.7.1-gcc
56:   LD_LIBRARY_PATH=/packages/python/3.6.4-ssl/lib:/packages/isl/0.16.1/lib:/packages/gmp/6.1/lib:/packages/mpfr/3.1_gmp6/lib:/packages/mpc/1.0_gmp6/lib:/packages/gcc/7.1/lib64:/packages/gcc/7.1/lib:/packages/openmpi/2.0_gcc-6/lib:/home/db2inst1/sqllib/lib:/home/users/khuck/tools/lib:/opt/R/lib/R/library/SJava/libs:/opt/R/lib/R/lib:/home/users/khuck/install/libunwind-1.1-gnu/lib
56:   LESSOPEN=||/usr/bin/lesspipe.sh %s
56:   LMOD_CMD=/usr/share/lmod/lmod/libexec/lmod
56:   LMOD_COLORIZE=yes
56:   LMOD_DEFAULT_MODULEPATH=/usr/local/packages/Modules/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles
56:   LMOD_DIR=/usr/share/lmod/lmod/libexec
56:   LMOD_FULL_SETTARG_SUPPORT=no
56:   LMOD_PKG=/usr/share/lmod/lmod
56:   LMOD_PREPEND_BLOCK=normal
56:   LMOD_SETTARG_CMD=:
56:   LMOD_VERSION=6.5.1
56:   LMOD_arch=x86_64
56:   LMOD_sys=Linux
56:   LOADEDMODULES=mpi/openmpi-2.0_gcc-6.4:gcc/7.1:python/3.6.4
56:   LOGNAME=khuck
56:   LS_COLORS=:no=00:fi=00:di=36:ln=01;33:pi=33:so=01;35:do=01;35:bd=01;37:cd=01;37:ex=01;32:or=01;37;41:mi=01;37;41:*.tar=01;31:*.tgz=01;31:*.gz=01;31:*.zip=01;31:*.sit=01;31:*.Z=01;31:*.bz2=01;31:*.z=01;31:*.rpm=01;31
56:   MAIL=/var/spool/mail/khuck
56:   MANPATH=/packages/python/3.6.4-ssl/man:/packages/gcc/7.1/share/man:/packages/openmpi/2.0_gcc-6/share/man:/usr/share/lmod/lmod/share/man::
56:   MODULEPATH=/usr/local/packages/Modules/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles
56:   MODULEPATH_ROOT=/packages/modulefiles
56:   MODULESHOME=/usr/share/lmod/lmod
56:   MPC=/packages/mpc/1.0_gmp6
56:   MPFR=/packages/mpfr/3.1_gmp6
56:   MPI=/packages/openmpi/2.0_gcc-6
56:   MPICC=mpicc
56:   MPICXX=mpicxx
56:   OLDPWD=/home/users/khuck/src/phylanx/tools/buildbot
56:   OPENSS_PLUGIN_PATH=/usr/local/lib64/openspeedshop/
56:   PATH=/usr/local/packages/cmake/3.9.3/bin:/packages/python/3.6.4-ssl/bin:/packages/gcc/7.1/bin:/packages/openmpi/2.0_gcc-6/bin:/home/users/khuck/build/jdk1.6.0_29/bin:/home/users/khuck/local/bin:/home/users/khuck/install/visit2_10_2.linux-x86_64/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/users/khuck/src/tau2/x86_64/bin:/home/db2inst1/sqllib/bin:/home/users/khuck/install/htop/2.0.2/bin:/home/users/khuck/tools/bin:.
56:   PKG_CONFIG_PATH=:/usr/local/packages/lapack/3.7.1-gcc/lib64/pkgconfig
56:   PWD=/home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo
56:   PYTHON=/packages/python/3.6.4-ssl/bin/python3.6
56:   PYTHONHOME=/packages/python/3.6.4-ssl
56:   PYTHONTOP=/packages/python/3.6.4-ssl
56:   SELINUX_LEVEL_REQUESTED=
56:   SELINUX_ROLE_REQUESTED=
56:   SELINUX_USE_CURRENT_RANGE=
56:   SHELL=/bin/bash
56:   SHLVL=1
56:   SSH_AUTH_SOCK=/tmp/ssh-eHI3oWXHdS/agent.102183
56:   SSH_CLIENT=128.223.202.144 45958 22
56:   SSH_CONNECTION=128.223.202.144 45958 128.223.202.67 22
56:   SSH_TTY=/dev/pts/0
56:   SVNROOT=http://precog.uoregon.edu/svn
56:   TAU_MPI=-mpiinc=/packages/openmpi/2.0_gcc-6/include -mpilib=/packages/openmpi/2.0_gcc-6/lib
56:   TERM=xterm
56:   USER=khuck
56:   XDG_DATA_DIRS=/home/users/khuck/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/
56:   XDG_RUNTIME_DIR=/run/user/14978
56:   XDG_SESSION_ID=19279
56:   _=/usr/local/packages/cmake/3.9.3/bin/ctest
56:   _LMFILES_=/usr/local/packages/Modules/modulefiles/mpi/openmpi-2.0_gcc-6.4:/usr/local/packages/Modules/modulefiles/gcc/7.1:/usr/local/packages/Modules/modulefiles/python/3.6.4
56:   _ModuleTable001_=X01vZHVsZVRhYmxlXz17WyJhY3RpdmVTaXplIl09MyxiYXNlTXBhdGhBPXsiL3Vzci9sb2NhbC9wYWNrYWdlcy9Nb2R1bGVzL21vZHVsZWZpbGVzIiwiL3Vzci9zaGFyZS9Nb2R1bGVzL21vZHVsZWZpbGVzIiwiL2V0Yy9tb2R1bGVmaWxlcyIsfSxbImNfcmVidWlsZFRpbWUiXT1mYWxzZSxbImNfc2hvcnRUaW1lIl09ZmFsc2UsZmFtaWx5PXt9LGluYWN0aXZlPXt9LG1UPXtnY2M9e1siRk4iXT0iL3Vzci9sb2NhbC9wYWNrYWdlcy9Nb2R1bGVzL21vZHVsZWZpbGVzL2djYy83LjEiLFsiZGVmYXVsdCJdPTAsWyJmdWxsTmFtZSJdPSJnY2MvNy4xIixbImxvYWRPcmRlciJdPTIscHJvcFQ9e30sWyJzaG9ydCJdPSJnY2MiLFsic3RhdHVzIl09ImFjdGl2ZSIsfSxtcGk9e1siRk4i
56:   _ModuleTable002_=XT0iL3Vzci9sb2NhbC9wYWNrYWdlcy9Nb2R1bGVzL21vZHVsZWZpbGVzL21waS9vcGVubXBpLTIuMF9nY2MtNi40IixbImRlZmF1bHQiXT0wLFsiZnVsbE5hbWUiXT0ibXBpL29wZW5tcGktMi4wX2djYy02LjQiLFsibG9hZE9yZGVyIl09MSxwcm9wVD17fSxbInNob3J0Il09Im1waSIsWyJzdGF0dXMiXT0iYWN0aXZlIix9LHB5dGhvbj17WyJGTiJdPSIvdXNyL2xvY2FsL3BhY2thZ2VzL01vZHVsZXMvbW9kdWxlZmlsZXMvcHl0aG9uLzMuNi40IixbImRlZmF1bHQiXT0wLFsiZnVsbE5hbWUiXT0icHl0aG9uLzMuNi40IixbImxvYWRPcmRlciJdPTMscHJvcFQ9e30sWyJzaG9ydCJdPSJweXRob24iLFsic3RhdHVzIl09ImFjdGl2ZSIsfSx9LG1wYXRoQT17Ii91c3IvbG9jYWwv
56:   _ModuleTable003_=cGFja2FnZXMvTW9kdWxlcy9tb2R1bGVmaWxlcyIsIi91c3Ivc2hhcmUvTW9kdWxlcy9tb2R1bGVmaWxlcyIsIi9ldGMvbW9kdWxlZmlsZXMiLH0sWyJzeXN0ZW1CYXNlTVBBVEgiXT0iL3Vzci9sb2NhbC9wYWNrYWdlcy9Nb2R1bGVzL21vZHVsZWZpbGVzOi91c3Ivc2hhcmUvTW9kdWxlcy9tb2R1bGVmaWxlczovZXRjL21vZHVsZWZpbGVzIixbInZlcnNpb24iXT0yLH0=
56:   _ModuleTable_Sz_=3
56:   activeharmony_path=/usr/local/packages/activeharmony/4.6.0-gcc
56:   basedir=/home/users/khuck/src/phylanx/tools
56:   boost_path=/usr/local/packages/boost/1.65.0-gcc7
56:   buildtype=Release
56:   host=delphi
56:   malloc=tcmalloc
56:   malloc_path=/usr/local/packages/gperftools/git-gcc7
56:   myarch=delphi-x86_64-Linux-gcc
56:   mycc=gcc
56:   mycflags=-fPIC
56:   mycxx=g++
56:   mycxxflags=-fPIC
56:   myfc=gfortran
56:   myldflags=-fPIC -Wl,--allow-multiple-definition
56:   otf2_path=/usr/local/packages/otf2-2.1
56:   papi_path=/usr/local/packages/papi/papi-knl/5.5.0/
56: {locality-id}: 0
56: {hostname}: [ (tcp:127.0.0.1:7910) ]
56: {process-id}: 118133
56: {function}: phylanx::execution_tree::extract_numeric_value
56: {file}: /home/users/khuck/src/phylanx/src/execution_tree/primitives/base_primitive.cpp
56: {line}: 989
56: {os-thread}: 0, worker-thread#0
56: {thread-id}: 0000000001d911e0
56: {thread-description}: hpx_main
56: {state}: state_running
56: {auxinfo}: 
56: {config}:
56:   HPX_WITH_AGAS_DUMP_REFCNT_ENTRIES=OFF
56:   HPX_WITH_APEX=TRUE
56:   HPX_WITH_APEX_NO_UPDATE=OFF
56:   HPX_WITH_ATTACH_DEBUGGER_ON_TEST_FAILURE=OFF
56:   HPX_WITH_AUTOMATIC_SERIALIZATION_REGISTRATION=ON
56:   HPX_WITH_CXX14_RETURN_TYPE_DEDUCTION=TRUE
56:   HPX_WITH_DEPRECATION_WARNINGS=ON
56:   HPX_WITH_DYNAMIC_HPX_MAIN=OFF
56:   HPX_WITH_GOOGLE_PERFTOOLS=OFF
56:   HPX_WITH_HPXMP=OFF
56:   HPX_WITH_INCLUSIVE_SCAN_COMPATIBILITY=ON
56:   HPX_WITH_IO_COUNTERS=ON
56:   HPX_WITH_IO_POOL=ON
56:   HPX_WITH_ITTNOTIFY=OFF
56:   HPX_WITH_LOGGING=ON
56:   HPX_WITH_MORE_THAN_64_THREADS=ON
56:   HPX_WITH_NATIVE_TLS=ON
56:   HPX_WITH_NETWORKING=ON
56:   HPX_WITH_PAPI=OFF
56:   HPX_WITH_PARCELPORT_ACTION_COUNTERS=OFF
56:   HPX_WITH_PARCELPORT_LIBFABRIC=OFF
56:   HPX_WITH_PARCELPORT_MPI=ON
56:   HPX_WITH_PARCELPORT_MPI_MULTITHREADED=ON
56:   HPX_WITH_PARCELPORT_TCP=ON
56:   HPX_WITH_PARCELPORT_VERBS=OFF
56:   HPX_WITH_PARCEL_PROFILING=ON
56:   HPX_WITH_SCHEDULER_LOCAL_STORAGE=OFF
56:   HPX_WITH_SPINLOCK_DEADLOCK_DETECTION=OFF
56:   HPX_WITH_STACKTRACES=ON
56:   HPX_WITH_SWAP_CONTEXT_EMULATION=OFF
56:   HPX_WITH_THREAD_BACKTRACE_ON_SUSPENSION=OFF
56:   HPX_WITH_THREAD_CREATION_AND_CLEANUP_RATES=OFF
56:   HPX_WITH_THREAD_CUMULATIVE_COUNTS=ON
56:   HPX_WITH_THREAD_DEBUG_INFO=OFF
56:   HPX_WITH_THREAD_DESCRIPTION_FULL=OFF
56:   HPX_WITH_THREAD_GUARD_PAGE=ON
56:   HPX_WITH_THREAD_IDLE_RATES=ON
56:   HPX_WITH_THREAD_LOCAL_STORAGE=OFF
56:   HPX_WITH_THREAD_MANAGER_IDLE_BACKOFF=ON
56:   HPX_WITH_THREAD_QUEUE_WAITTIME=OFF
56:   HPX_WITH_THREAD_STACK_MMAP=ON
56:   HPX_WITH_THREAD_STEALING_COUNTS=ON
56:   HPX_WITH_THREAD_TARGET_ADDRESS=OFF
56:   HPX_WITH_TIMER_POOL=ON
56:   HPX_WITH_TUPLE_RVALUE_SWAP=ON
56:   HPX_WITH_UNWRAPPED_COMPATIBILITY=ON
56:   HPX_WITH_VALGRIND=OFF
56:   HPX_WITH_VERIFY_LOCKS=OFF
56:   HPX_WITH_VERIFY_LOCKS_BACKTRACE=OFF
56:   HPX_WITH_VERIFY_LOCKS_GLOBALLY=OFF
56: 
56:   HPX_PARCEL_MAX_CONNECTIONS=512
56:   HPX_PARCEL_MAX_CONNECTIONS_PER_LOCALITY=4
56:   HPX_AGAS_LOCAL_CACHE_SIZE=4096
56:   HPX_HAVE_MALLOC=tcmalloc
56:   HPX_PREFIX (configured)=/home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/hpx-RelWithDebInfo
56:   HPX_PREFIX=/home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/hpx-RelWithDebInfo
56: {version}: V1.2.0-trunk (AGAS: V3.0), Git: 79dabaa1b4
56: {boost}: V1.65.0
56: {build-type}: release
56: {date}: Oct  1 2018 14:14:10
56: {platform}: linux
56: {compiler}: GNU C++ version 7.1.0
56: {stdlib}: GNU libstdc++ version 20170502
56: {what}: <unknown>: primitive_argument_type does not hold a numeric value type (type held: 'phylanx::ast::nil'): HPX(bad_parameter)
56: 
56: terminate called after throwing an instance of 'hpx::detail::exception_with_info<hpx::exception>'
56:   what():  <unknown>: primitive_argument_type does not hold a numeric value type (type held: 'phylanx::ast::nil'): HPX(bad_parameter)
56: 
56: generate_tree_test:118133 terminated with signal 6 at PC=7f0902a70277 SP=7ffcaf88a268.  Backtrace:
56: /lib64/libc.so.6(gsignal+0x37)[0x7f0902a70277]
56: /lib64/libc.so.6(abort+0x148)[0x7f0902a71968]
56: /packages/gcc/7.1/lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x125)[0x7f09033b11b5]
56: /packages/gcc/7.1/lib64/libstdc++.so.6(+0x8efa6)[0x7f09033aefa6]
56: /packages/gcc/7.1/lib64/libstdc++.so.6(+0x8eff1)[0x7f09033aeff1]
56: /packages/gcc/7.1/lib64/libstdc++.so.6(+0x8ef9a)[0x7f09033aef9a]
56: /home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/hpx-RelWithDebInfo/lib/libhpx.so.1(_ZN3hpx12runtime_impl17rethrow_exceptionEv+0xdc)[0x7f090655432c]
56: /home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/hpx-RelWithDebInfo/lib/libhpx.so.1(_ZN3hpx12runtime_impl3runERKNS_4util8functionIFivELb0EEE+0x3d)[0x7f0906553b7d]
56: /home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/hpx-RelWithDebInfo/lib/libhpx.so.1(_ZN3hpx6detail3runERNS_7runtimeERKNS_4util8functionIFiRN5boost15program_options13variables_mapEELb0EEES8_NS_12runtime_modeENS3_15unique_functionIFvvELb0EEESG_+0x5e6)[0x7f090652efe6]
56: /home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/hpx-RelWithDebInfo/lib/libhpx.so.1(_ZN3hpx6detail12run_or_startEbSt10unique_ptrINS_7runtimeESt14default_deleteIS2_EERNS_4util21command_line_handlingENS6_15unique_functionIFvvELb0EEESB_+0x86)[0x7f090652f9f6]
56: /home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/hpx-RelWithDebInfo/lib/libhpx.so.1(_ZN3hpx6detail12run_or_startERKNS_4util8functionIFiRN5boost15program_options13variables_mapEELb0EEERKNS4_19options_descriptionEiPPcOSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISM_EENS1_15unique_functionIFvvELb0EEESS_NS_12runtime_modeEb+0x2f3)[0x7f090652fd93]
56: /home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/bin/generate_tree_test[0x41e530]
56: /home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/bin/generate_tree_test[0x41d9ed]
56: /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f0902a5c445]
56: /home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/bin/generate_tree_test[0x411913]
56: Base command is "/home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/bin/generate_tree_test --hpx:threads=1 --hpx:localities=1"
56: Executing command: /home/users/khuck/src/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/bin/generate_tree_test --hpx:threads=1 --hpx:localities=1 --hpx:node=0
1/1 Test #56: tests.unit.execution_tree.generate_tree ...***Failed    1.01 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   1.06 sec

The following tests FAILED:
	 56 - tests.unit.execution_tree.generate_tree (Failed)
Errors while running CTest
```

**Comment by hkaiser** [comment]
@khuck thanks for this. I changed the 'return value' for the file write primitives and that causes the problem. I'll fix it.

**Comment by khuck** [comment]
@hkaiser I detected one last one - there are fwrite() calls from one thread, from:
https://github.com/STEllAR-GROUP/phylanx/blob/master/src/ir/node_data.cpp#L1419
and
https://github.com/STEllAR-GROUP/phylanx/blob/master/src/ir/node_data.cpp#L1428

Unfortunately, TAU isn't giving me the callsite location in depth order, but alphabetical.  Hrm.

**Comment by hkaiser** [comment]
@khuck thanks. That should be fixed now as well.

**Pull request merged**
