### PR TITLE
Fixing compiler

### LINKED ISSUE #491: Variables PhySL functions are written to only once
Variables inside PhySL functions get their value the first time `define` is evaluated.

e.g.
```scheme
define(f, a, block(
    define(b, a),
    cout(a),
    cout(b),
    0
))
f(1)
f(2)
```
Output:
```
1
1
2
1
```

### LINKED ISSUE #492: Can't call a Lambda
The code
```
from phylanx.ast import Phylanx

@Phylanx
def foo():
    f = lambda a : print(a)
    f(1)

foo()
```
Yields the message
```
Traceback (most recent call last):
  File "lam.py", line 8, in <module>
    foo()
  File "/root/.local/lib/python3.5/site-packages/phylanx-0.0.1-py3.5-linux-x86_64.egg/phylanx/ast/transformation.py", line 689, in __call__
    return et.eval(self.f.__name__, self.cs, *nargs)
RuntimeError: <unknown>(5, 25): access-argument$a:: argument count out of bounds, expected at least 1 argument(s) while only 0 argument(s) were supplied: HPX(bad_parameter)
```
Apparently, the argument count is not correctly identified when calling lambdas. For reference, the PhySL code is here:
```
define(
    foo,
    block(
        define(
            f,
            lambda(
                a,
                block(
                    cout(a)
                )
            )
        ),
        (
            f(1)
        )
    )
)
```

### LINKED ISSUE #494: len operation does not support np.array
The code
```
@Phylanx(debug=True)
def Phylanx_len_test(input_para):
    local_input_para = input_para
    print("Phylanx precision: ", len(local_input_para), '\n')


def Python_len_test(input_para):
    print("Python len: ", len(input_para), '\n')


b = np.array([1, 2, 3])

Python_len_test(b)
Phylanx_len_test(b)
```
yields information:
```
define(
    Phylanx_len_test,
    input_para,
    block(
        define(local_input_para, input_para),
        (
            cout(
                "Phylanx precision: ",
                len(local_input_para),
                "
"
            )
        )
    )
)
Python len:  3 

Traceback (most recent call last):
  File "/root/PycharmProjects/nn/add_test.py", line 235, in <module>
    Phylanx_len_test(b)
  File "/root/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/transformation.py", line 685, in __call__
    return et.eval(self.f.__name__, self.cs, *nargs)
RuntimeError: <unknown>(225, 33): len:: len_operation accepts a list or a string as operand: HPX(bad_parameter)

Process finished with exit code 1
```

### LINKED ISSUE #509: Empty list defined inside Phylanx function has an issues
Empty list defined inside Phylanx function can automatically append the input list of the function. 
For example,
code
```
from phylanx.ast import *
import numpy as np


@Phylanx(debug=True)
def testing_list(a):
    b = []
    print(b)


a = [4, 3, 2, 1]
testing_list(a)
```
yields
```
define(
    testing_list,
    a,
    block(
        define(
            b,
            make_list()
        ),
        (
            cout(b)
        )
    )
)
make_list(make_list(4, 3, 2, 1))
```

### LINKED ISSUE #510: Empty np.array defined inside Phylanx function has an issues
Similar to #509 but this time it is numpy array.
Empty np.array defined inside Phylanx function can automatically append the input np.array of the function.
For example,
code
```py
from phylanx.ast import *
import numpy as np


@Phylanx(debug=True)
def testing_array(a):
    b = np.array([])
    print(b)


a = np.array([4, 3, 2, 1])
testing_array(a)
```
yields,
```
define(
    testing_array,
    a,
    block(
        define(
            b,
            hstack()
        ),
        (
            cout(b)
        )
    )
)
[4, 3, 2, 1]
```

But if you put `b = np.array([1])`, the result is correct.

### LINKED ISSUE #512: Local variable remained unchanged after the 1st time calling the fucntion
I expect 
```
1
2
```
to be returend by the following function
```py
from phylanx.ast import *
import numpy as np


@Phylanx
def foo1(x):
    local_x = x
    return local_x

c = 1
d = 2
print(foo1(c))
print(foo1(d))
```
however, it returns
```
1
1
```
Therefore, the following test fails
```py
@Phylanx
def foo1(x):
    local_x = x
    return local_x

c = 1
d = 2

assert (foo1(c) == 1)
assert (foo1(d) == 2)
```

### LINKED ISSUE #516: For loop (map:: function) failed after first time of execution
I am checking the lastest branch of `fixing_compiler` with `commit e385f1c427d7d8b2cf93d56b6f9f3efdea7387ae`
I expect 
```py
hello
hello
hello
```
to be returned by the following code
```py
from phylanx.ast import *
import numpy as np


@Phylanx
def foo1():
    for i in range(3):
        print("hello")


foo1()
```
however, it complains
```py
Traceback (most recent call last):
  File "PATH/PycharmProjects/nn/add_test.py", line 11, in <module>
    foo1()
  File "PATH/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/transformation.py", line 701, in __call__
    return et.eval(self.f.__name__, self.cs, *nargs)
hello
RuntimeError: <unknown>(7, 4): map:: the first argument to map must be an invocable object: HPX(bad_parameter)
```

### PR DESCRIPTION
**Pull request by hkaiser**
This PR  represents a major redesign of the PhySL compiler with the purpose of cleaning up its implementation and fixing a couple of problems we see.

This fixes several issues in the PhySL compiler:

- fixes #491
- fixes #509
- fixes #510 
- fixes #512
- fixes #516
- fixes #494
- fixes #492

For now this PR is not ready to be merged. It is still work in progress. It serves mainly the purpose of tracking the issues fixed.

### CODE REVIEW

**Comment by hkaiser** [comment]
@weilewei why have you closed this PR?

**Comment by weilewei** [comment]
@hkaiser sorry, this is a mistake. I don't know what did I do on my computer.

**Comment by weilewei** [comment]
@hkaiser does it work now?

**Comment by hkaiser** [comment]
@weilewei yes, thanks!

**Pull request merged**
