### PR TITLE
Adding variable._keras_shape attribute

### LINKED ISSUE #1054: Add support for variable._keras_shape

### PR DESCRIPTION
**Pull request by hkaiser**
- adding constructor variable(shape, dtype, name, constraint)

Fixes #1054

### CODE REVIEW

**Comment by taless474** [comment]
The following code:
```python
from phylanx import Phylanx, PhylanxSession, execution_tree
import numpy as np

PhylanxSession.init(1)

def variable(value, dtype=None, name=None):
	if dtype is None:
		dtype = "float64"
	from phylanx.ast.physl import PhySL
	if isinstance(value, PhySL.eval_wrapper):
		return execution_tree.variable(value.code(), dtype)
	if isinstance(value, execution_tree.variable):
		return value
	return execution_tree.variable(value, dtype=dtype, name=name)

def eval(x):
	return x.eval()
	
	
x_elem1 = variable(np.array([1,2,3,4]))
x_elem2 = variable(np.array([[1,2,3,4],[5,6,7,8]]))
x_elem3 = variable(np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]]))

inputs = [x_elem1,x_elem2,x_elem3]

shapes = []
for x_elem in inputs:
	if hasattr(x_elem, '_keras_shape'):
		shapes.append(x_elem._keras_shape)
print(shapes)
```
results in:
```pytb
[(), (), ()]
```

**Comment by hkaiser** [comment]
@taless474 at least it doesn't blow up or anything ;-)

**Comment by hkaiser** [comment]
@taless474 this should be fine now.

**Comment by taless474** [comment]
Thank you.

**Pull request merged**
