### PR TITLE
hyperlda

### PR DESCRIPTION
**Pull request by ct-clmsn**
numpy implementation of hyper-parameterized lda as per [mallet](https://github.com/mimno/Mallet)

### CODE REVIEW

**Comment by ct-clmsn** [comment]
@hkaiser if i need to modify the portions that use [numpy.ma](https://docs.scipy.org/doc/numpy/reference/maskedarray.html), just say the word!

**Comment by ct-clmsn** [comment]
@hkaiser flake8 *really* hates my conditional expressions.

**Comment by hkaiser** [comment]
> i'll be adding a phylanx annotated version of this code next. 

Thanks! Please let us know if you run into missing capabilities on the Phylanx end.

> do ya'll want me to hand-write this code in PhySL?

The benefit of this would be minimal, I think. We can always generate the PhySL version from your @Phylanx-annotated code, if needed.

**Comment by ct-clmsn** [comment]
@hkaiser I gave the code a run through with the @Phylanx('PhySL') annotation; it crashed with a 'src/tcmalloc.cc:278] Attempt to free invalid pointer' error. What method do ya'll use for debugging these issues?

**Comment by justwagle** [comment]
@ct-clmsn try ld preloading the tcmqlloc library. That should help. Looks like python is using the system allocator and you built phylanx with tcmalloc.

**Comment by ct-clmsn** [comment]
@justwagle thanks! i tried `LD_LOAD=<path-to-libtcmalloc> python phylanx_lra_csv.py` and got the same issue. will continue to fiddle until it works. oh, i'm using ubuntu gcc 7.3.0.

@hkaiser fair enough! thanks for clearing the PR! will shift back to randomforest.

**Comment by hkaiser** [comment]
@ct-clmsn Could you try `LD_PRELOAD=<path-to-libtcmalloc> python phylanx_lra_csv.py` instead, please?

**Comment by ct-clmsn** [comment]
@justwagle @hkaiser we are in business! thanks again! i'm now getting transformation errors! progress!

**Pull request merged**
