### PR TITLE
Make sure map() and parallel_map() accept only lists (ranges) as their arguments.

### PR DESCRIPTION
**Pull request by hkaiser**
- flyby: change `'()` to `make_list()` in tests

### CODE REVIEW

**Comment by hkaiser** [comment]
@stevenrbrandt this should at least prevent map() (and parallel_map()) from accepting anything but lists. Please verify.

**Comment by stevenrbrandt** [comment]
@hkaiser is that the right solution? Do we want the code below to not work when @Phylanx() is added?
```
import numpy as np
vec = np.array([1,2,3,4])

def iter_vec(v):
    for i in v:
        print(i)

iter_vec(vec)
```

**Comment by hkaiser** [comment]
@stevenrbrandt I'm not sure whether iteration over numpy arrays should work, I'm open to discussion here. This PR solves the orthogonal issue that map (and parallel_map) were accepting any value as iterables.

**Comment by stevenrbrandt** [comment]
@hkaiser my concern is whether we can write simple kernels that can be optimized by polyhedral compilers. It may be that we prefer loops of the form:
```
for i in range(1,len(x)-1):
   y[i] = x[i+1]+x[i-1]
```

**Pull request merged**
