### PR TITLE
PhySL QR Decomposition

### PR DESCRIPTION
**Pull request by ct-clmsn**
Implementation of QR decomposition as presented in [JAMA](https://math.nist.gov/javanumerics/jama/). PhySL interpreter reports this error,

```
physl: exception caught:
the define() operation requires that all arguments are represented as variable names (not expressions): HPX(bad_parameter)
```
I am not sure where the bug is located.

### CODE REVIEW

**Comment by hkaiser** [comment]
@ct-clmsn I think the problem is here: https://github.com/STEllAR-GROUP/phylanx/pull/229/files#diff-8ca483421ba3c791cf5a94ffd72aa595R231 ('X' needs to be reference inside the block, not outside of it).

**Comment by ct-clmsn** [comment]
@hkaiser thanks for the help! hit an exception working with slices - should this be expressed differently?

physl: exception caught:
couldn't fully pattern-match the given expression: (s * slice(QR, i, k) + slice(B, i, j)): HPX(bad_parameter)

**Comment by hkaiser** [comment]
> physl: exception caught:
> couldn't fully pattern-match the given expression: `(s * slice(QR, i, k) + slice(B, i, j))`: HPX(bad_parameter)

yes, I know the pattern matching is not perfect. Try fully parenthesizing the expression, then it will work:
 
    ((s * slice(QR, i, k)) + slice(B, i, j))

I'll make a note to investigate this problem.

**Comment by ct-clmsn** [comment]
@hkaiser ah - apologies, it's not a problem. wasn't sure what the exception meant.

**Comment by parsa** [comment]
This PR has been here for a while. Should we kill it or merge it?

**Comment by ct-clmsn** [comment]
@parsa I will pick this back up.

**Comment by parsa** [comment]
@ct-clmsn you might wish to know that @scheherzade is currently working on a QR-decomposition primitive that sits directly on top of Blaze.

**Comment by ct-clmsn** [comment]
@parsa probably time to close this out given @scheherzade is at a solution.

**Pull request closed without merging**
