### PR TITLE
Use shared_ptr to an array only if it's supported

### PR DESCRIPTION
**Pull request by hkaiser**

### CODE REVIEW

**Comment by taless474** [comment]
Thanks for the PR. I see these errors:
https://gist.github.com/taless474/51e0f5d7b30600d7ae0193fd3b923ec2

**Comment by hkaiser** [comment]
@taless474 Uhh, these errors are unrelated, no idea what's causing those. Do you use a released Blaze version or is this Blaze top of master?

**Comment by taless474** [comment]
I am using the blaze package installed on Rostam which I think is the last release (Blaze 3.7)
I will install Blaze from its master and try it again, thank you.

**Comment by taless474** [comment]
It worked properly. Thank you very much.

**Pull request merged**
