### PR TITLE
Supporting new _Constant handling in Python 3.8

### LINKED ISSUE #1255: Passing a dict to Phylanx is not possible
```
from phylanx import Phylanx


dict_nn = {
    "Patrick " : "Cool"
    }

@Phylanx(debug=True)
def change(data):
    data["Patrick"] = "Mega cool"
    
    
if __name__ == "__main__":
    
    change(dict_nn)
```

running this code without the decorator works. Running this code with the decorator results in 
```

diehlpk@localhost ~/g/SOO (phylanx_share)> python example.py
Traceback (most recent call last):
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 383, in _compile_or_load
    self.ir = self._apply_rule(self.python_tree.body[0])
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 1028, in _FunctionDef
    body = self._block(node.body)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 952, in _block
    block = tuple(map(self._apply_rule, node))
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 684, in _Assign
    symbol = self._apply_rule(node.targets[0])
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 1294, in _Subscript
    slice_ = self._apply_rule(node.slice)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 1090, in _Index
    return self._apply_rule(node.value)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 919, in _Constant
    return self._apply_rule(node.value)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "<string>", line 1, in <module>
AttributeError: 'PhySL' object has no attribute '_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 15, in <module>
    change(dict_nn)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/transducer.py", line 168, in __call__
    result = self.backend.call(*mapped_args, **mapped_kwargs)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 566, in call
    self._ensure_global_state()
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 435, in _ensure_global_state
    PhySLFunction.compile()
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 348, in compile
    func.compile_function()
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 342, in compile_function
    self.physl._ensure_is_compiled()
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 448, in _ensure_is_compiled
    self._compile_or_load()
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 405, in _compile_or_load
    self.ir = self._apply_rule(self.python_tree.body[0])
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 1028, in _FunctionDef
    body = self._block(node.body)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 952, in _block
    block = tuple(map(self._apply_rule, node))
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 684, in _Assign
    symbol = self._apply_rule(node.targets[0])
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 1294, in _Subscript
    slice_ = self._apply_rule(node.slice)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 1090, in _Index
    return self._apply_rule(node.value)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 919, in _Constant
    return self._apply_rule(node.value)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "<string>", line 1, in <module>
AttributeError: 'PhySL' object has no attribute '_str'
FATAL: exception not rethrown
```

### PR DESCRIPTION
**Pull request by hkaiser**
Fixes #1255

### CODE REVIEW

**Comment by diehlpk** [comment]
@hkaiser It seems that the patch does not work as expected. I slightly modified the previous example

```
from phylanx import Phylanx


dict_nn = {
    "Patrick" : "Cool"
    }

@Phylanx(debug=True)
def change(data):
    data["Patrick"] = "Mega cool"
    
    
if __name__ == "__main__":
    
    change(dict_nn)
    
    print("Test")
    print(dict_nn["Patrick"])
```

and the value of the key `"Patrick"` seems not to be changed, and we see the error `FATAL: exception not rethrown`. This is the output 

```
diehlpk@localhost ~/g/SOO (phylanx_share)> python example.py
define(
    change,
    data,
    store(
        slice(data, "Patrick"),
        "Mega cool"
    )
)
Test
Cool
FATAL: exception not rethrown
```

**Comment by diehlpk** [comment]
In addition, @NanmiaoWu gets this error

photo5145823592221616323

**Comment by hkaiser** [comment]
> In addition, @NanmiaoWu gets this error
> 
> photo5145823592221616323

This looks like a problem with the Phylanx installation (the plugins are not found). Does any other Phylanx script work?

**Comment by hkaiser** [comment]
@diehlpk try this instead, please:
```
@Phylanx(debug=True)
def change(data):
    data["Patrick"] = "Mega cool"

if __name__ == "__main__":
    dict_nn = change(dict_nn)
    
    print("Test")
    print(dict_nn["Patrick"])
```

**Comment by diehlpk** [comment]
> @diehlpk try this instead, please:
> 
> ```
> @Phylanx(debug=True)
> def change(data):
>     data["Patrick"] = "Mega cool"
> 
> if __name__ == "__main__":
>     dict_nn = change(dict_nn)
>     
>     print("Test")
>     print(dict_nn["Patrick"])
> ```

@hkaiser This does not work as well, since `dict_nn` becomes `none` and I can use the key of the dict.

```
diehlpk@localhost ~/g/SOO (phylanx_share)> python example.py
define(
    change,
    data,
    store(
        slice(data, "Patrick"),
        "Mega cool"
    )
)
Test
Traceback (most recent call last):
  File "example.py", line 18, in <module>
    print(dict_nn["Patrick"])
TypeError: 'NoneType' object is not subscriptable
FATAL: exception not rethrown
```

**Comment by diehlpk** [comment]
@hkaiser We missed the `return data` and it works.

```
@Phylanx(debug=True)
def change(data):
    data["Patrick"] = "Mega cool"
    return data


if __name__ == "__main__":
    dict_nn = change(dict_nn)
    
    print("Test")
    print(dict_nn["Patrick"])
```

**Comment by hkaiser** [comment]
Merging this despite the problem in traverse_ast - will fix that separately.

**Pull request merged**
