### PR TITLE
Adding support for len() on dictionaries

### LINKED ISSUE #1224: Can't get length of a dictionary
As reported by @stevenrbrandt here: https://github.com/STEllAR-GROUP/docker-containers/issues/6

### PR DESCRIPTION
**Pull request by hkaiser**
- unified implementation for len_operation()

Fixes #1224

### CODE REVIEW

**Comment by hkaiser** [comment]
@stevenrbrandt please verify whether this solve the issue you reported.

**Comment by stevenrbrandt** [comment]
I can't build this branch. I keep getting
```
[ 51%] Built target primitives.controls_dir
/usr/bin/ld: /tmp/cc3civTu.ltrans8.ltrans.o: relocation R_X86_64_PC32 against undefined symbol `_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev' can not be used when making a shared object; recompile with -fPIC
```

**Comment by stevenrbrandt** [comment]
This appears to be `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()`

Does that mean the string library is compiled without -fPIC?

**Comment by hkaiser** [comment]
> X86_64_PC

Which module (target) is failing to compile?

**Comment by stevenrbrandt** [comment]
I managed to get past the weird compilation issue. This code works for me.

**Pull request merged**
