### PR TITLE
initial import of hyperparameterized lda

### PR DESCRIPTION
**Pull request by ct-clmsn**
first import of the hyper_lda implementation

### CODE REVIEW

**Comment by ct-clmsn** [comment]
@hkaiser I've a couple more mods to make. Will be making updates on this branch. Hope that doesn't mix things up too terribly.

**Comment by hkaiser** [comment]
@ct-clmsn no worries. Things will be slow for the next couple of weeks anyways...

**Comment by hkaiser** [comment]
@ct-clmsn can we close this without merging now? Is this now a duplicate of #798?

**Comment by ct-clmsn** [comment]
@hkaiser sure thing will get that done today.

**Pull request closed without merging**
