### PR TITLE
Distributing

### PR DESCRIPTION
**Pull request by stevenrbrandt**
This pull request makes the find_here() and find_all_localitiies() primitives available to Python / Phylanx.

### CODE REVIEW

**Comment by hkaiser** [comment]
As it turns out, we already have two primitives: `locality()` and `num_localities()` (see: https://github.com/STEllAR-GROUP/phylanx/blob/master/src/execution_tree/primitives/debug_output.cpp#L81-L145) We should rename `locality()` to `find_here()`, obviously, and just add your `find_all_localities()`.

**Comment by hkaiser** [comment]
@stevenrbrandt there are probably tests relying on `locality()`. Those need fixing as well.

**Comment by hkaiser** [comment]
@stevenrbrandt please rebase onto master. That should make the tests compile again.

**Comment by stevenrbrandt** [comment]
@hkaiser all checks are passed, waiting for a review.

**Pull request merged**
