### PR TITLE
Update LRA example to use more NumPy functions.

### PR DESCRIPTION
**Pull request by rtohid**

### CODE REVIEW

**Comment by aserio** [comment]
@rtohid Didn't we want to use less NumPy and more Phylanx functions?

**Comment by rtohid** [comment]
@aserio This example demonstrates that Phylanx supports NumPy. You can find the pure Phylanx version [here](https://github.com/STEllAR-GROUP/phylanx/blob/master/examples/algorithms/phylanx_lra_csv.py).

**Comment by aserio** [comment]
You are correct, I was mistaken.

**Comment by aserio** [comment]
Merging as this change is unrelated to the CircleCI issues.

**Pull request merged**
