### PR TITLE
Fixing currently failing remote test

### LINKED ISSUE #801: Distributed buildbot tests failing
mpi and tcp tests are failing with the following message:

```
{what}: <unknown>(6, 5): access-function$fx:: the variable 'fx' is unbound in the current execution environment: HPX(bad_parameter): : 
```

See http://ktau.nic.uoregon.edu:8020/#/builders/7/builds/140/steps/14/logs/stdio for details.

### PR DESCRIPTION
**Pull request by hkaiser**
Fixes #801

### CODE REVIEW

**Comment by khuck** [comment]
@hkaiser I can confirm that this fixes the buildbot tests!

**Comment by khuck** [comment]
@parsa @hkaiser can we deploy this?

**Comment by parsa** [comment]
@khuck not yet.

**Comment by khuck** [comment]
@hkaiser @parsa What’s the holdup?

**Comment by parsa** [comment]
Okay, I'm done. This is ready to merge once CircleCI is done and green.

**Comment by hkaiser** [comment]
@parsa thanks for looking into this!

**Pull request merged**
