### PR TITLE
Allow for iteration over arrays using map

### PR DESCRIPTION
**Pull request by hkaiser**
- flyby: add unary Not to translation layer

### CODE REVIEW

**Comment by hkaiser** [comment]
@parsa, @stevenrbrandt is this what you need? Does it work for your use cases?

**Comment by stevenrbrandt** [comment]
Interesting observation... the following code works perfectly:
```
import numpy as np
from phylanx.ast import Phylanx

@Phylanx()
def iter():
    a = hstack(1,2,3,4)
    for i in a:
        print(i)

iter()
```
But if I leave off the call to iter, I get a core dump at shutdown
```
1
2
3
4
terminate called after throwing an instance of 'std::runtime_error'
  what():  scoped_acquire::dec_ref(): thread state must be current!
Aborted (core dumped)
```

**Comment by stevenrbrandt** [comment]
After more testing, I think the dec_ref() thing is not related to leaving off the iter().

**Comment by stevenrbrandt** [comment]
I see no direct tests of the new functionality (though there is some new testing of lambda's). Maybe something like this should be added? (Note: it passes)
```
import numpy as np

a = np.linspace(0,5,6)
b = np.zeros(a.shape)

@Phylanx
def copyme(a,b):
    n = 0
    for i in a:
        b[n] = i
        n += 1
    return b

b = copyme(a,b)

assert np.all(a == b)
```

**Comment by hkaiser** [comment]
Yes, the dec_ref problem is related to a bug in how we handle the GIL.

**Pull request merged**
