### PR TITLE
Making the detail::extract_function_name unique

### PR DESCRIPTION
**Pull request by khuck**
The detail::extract_function_name function in generic_operation
doesn't seem to be the one that gets called.  Changing its name
to something unique (detail::extract_function_name_generic)
fixes issue #767.

### CODE REVIEW

**Comment by hkaiser** [comment]
@khuck I'll have a look at the two failing tests.

**Comment by khuck** [comment]
Are the test failures even related to this change?  It doesn’t seem that they are.

**Comment by hkaiser** [comment]
@khuck I think the test failures are related. The problem was that two functions had the same name and the loader had sometimes picked one, sometimes the other (depending on the load order of the shared libraries). The tests luckily always picked the other function, which made them pass...

**Comment by khuck** [comment]
@hkaiser Ah, of course.  Is there a way to catch this again in the future?  Having two symbols with the same namespace/name, that is.  Or should that function have only visibility within the compilation unit?  Regardless, do you want me to fix it, or are you doing it?

**Comment by hkaiser** [comment]
@khuck if you know how to fix it - be my guest. I would move the function you changed next to the other one (source file-wise). That should make it clear we have two different versions. Additionally (or even as a first thing) I'd try to unify the two functions (this was the intent, actually, but I missed removing one of the function instances, which caused the issues we're seeing).

**Comment by khuck** [comment]
@hkaiser I made one generic function in primitive_component_base, and all children use that.  I am still getting these tests failures, though - are they related?

```
 19/200 Test  #19: tests.regressions.execution_tree.out_of_scope_variable_232 .............***Failed    0.79 sec
/dev/shm/now/phylanx/tests/regressions/execution_tree/out_of_scope_variable_232.cpp(39): test 'std::string(e.what()) == "code(5, 13): couldn't find variable 'n' in symbol table: " "HPX(bad_parameter)"' failed in function 'int main(int, char**)': '%1%(%2%, %3%): %4%: HPX(bad_parameter)' != 'code(5, 13): couldn't find variable 'n' in symbol table: HPX(bad_parameter)'
0 sanity checks and 1 test failed.
Base command is "/dev/shm/now/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/bin/out_of_scope_variable_232_test --hpx:threads=1 --hpx:localities=1"
Executing command: /dev/shm/now/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/bin/out_of_scope_variable_232_test --hpx:threads=1 --hpx:localities=1 --hpx:node=0
```

```
 28/200 Test  #28: tests.regressions.python.python.466_compiler_problems ..................***Failed    1.58 sec
Traceback (most recent call last):
  File "/dev/shm/now/phylanx/tests/regressions/python/466_compiler_problems.py", line 11, in <module>
    PhylanxSession.init(1)
  File "/dev/shm/now/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/python/build/lib.linux-x86_64-3.6/phylanx/core/config.py", line 33, in init
    init_hpx_runtime(PhylanxSession.cfg)
RuntimeError
```

```
 45/200 Test  #45: tests.regressions.python.python.exception_swallowed_369 ................***Failed    1.61 sec
Traceback (most recent call last):
  File "/dev/shm/now/phylanx/tests/regressions/python/exception_swallowed_369.py", line 21, in <module>
    print('addem=(', addem(np.zeros((2, 4)), np.zeros((2, 3))), ')')
  File "/dev/shm/now/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/python/build/lib.linux-x86_64-3.6/phylanx/ast/transducer.py", line 82, in __call__
    result = self.backend.call(args)
  File "/dev/shm/now/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/python/build/lib.linux-x86_64-3.6/phylanx/ast/physl.py", line 369, in call
    self.file_name, func_name, PhySL.compiler_state, *args)
RuntimeError: %1%%2%: %3%:: %4%: HPX(bad_parameter)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dev/shm/now/phylanx/tests/regressions/python/exception_swallowed_369.py", line 27, in <module>
    assert (str(e).endswith(expected))
AssertionError
```

```
180/200 Test #180: tests.unit.python.execution_tree.config_hpx ............................***Failed    1.49 sec
Traceback (most recent call last):
  File "/dev/shm/now/phylanx/tests/unit/python/execution_tree/config_hpx.py", line 26, in <module>
    PhylanxSession.config(cfg)
  File "/dev/shm/now/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/python/build/lib.linux-x86_64-3.6/phylanx/core/config.py", line 43, in config
    init_hpx_runtime(cfg)
RuntimeError
```

**Comment by hkaiser** [comment]
@khuck all of the test failures you listed above will be fixed once https://github.com/STEllAR-GROUP/hpx/pull/3677 is merged.

**Comment by khuck** [comment]
@hkaiser Confirmed - when I build HPX with that PR, all Phylanx tests pass for me.  Not sure what's holding up your PR.  When it's merged, I'll update this branch and re-run the CI tests.

**Comment by hkaiser** [comment]
@khuck somebody needs to review and accept that PR. If you left a comment over there I would be able to merge it.

**Pull request merged**
