### PR TITLE
Adding 3D support to the argmin and argmax primitives

### PR DESCRIPTION
**Pull request by hkaiser**
- unify argmin/argmax implementations

Working towards solving #741

### CODE REVIEW

**Comment by taless474** [comment]
I was reading `argmax` a few days ago and I think x_axis and y_axis are written the other way in comparison to their numpy versions [(here)](https://github.com/STEllAR-GROUP/phylanx/commit/fa74da24b30ee9203bf62f21361d72e3c4713142).

**Comment by hkaiser** [comment]
@taless474 would you have a test-case demonstrating the problem you're referring to?

**Comment by hkaiser** [comment]
@taless474 everything should be ok now.

**Comment by taless474** [comment]
Thanks.

**Pull request merged**
