### PR TITLE
node_data<bool> --> node_data<uint8_t>

### PR DESCRIPTION
**Pull request by hkaiser**
This is to avoid using `vector<bool>` which prevents problems in pybind11

### CODE REVIEW

**Comment by hkaiser** [comment]
@kawilliams this should resolve your issues with pybind11 you mentioned on IRC. Please verify.

**Comment by kawilliams** [comment]
@hkaiser Unfortunately, I got another error. This is what I did:
#make clean and rm -rf build
git pull
git checkout 81aa278c5781c885c5e00be42337b70e85f13d91
mkdir build
cd build
cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS=-stdlib=libc++ -DCMAKE_BUILD_TYPE=Debug  -DHPX_DIR=/home/kwilliams/software/hpx/build/lib/cmake/HPX -Dblaze_DIR=/home/kwilliams/opt/share/blaze/cmake -Dpybind11_DIR=/opt/mn/pybind11/2.2.0/share/cmake/pybind11 ..

Which works fine. Then
make -j4

I got the error:
[ 97%] Linking CXX shared module ../../bin/_phylanxd.cpython-34m.so
/opt/mn/binutils/2.28/bin/ld: CMakeFiles/phylanx_py.dir/init_hpx.cpp.o: .preinit_array section is not allowed in DSO
/opt/mn/binutils/2.28/bin/ld: failed to set dynamic section sizes: Nonrepresentable section on output
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/_phylanxd.cpython-34m.so] Error 1
make[1]: *** [python/src/CMakeFiles/phylanx_py.dir/all] Error 2
make: *** [all] Error 2

**Comment by hkaiser** [comment]
@kawilliams Yes, this is a known issue which will be solved asap. Please just edit that file and replace `.preinitarray` with `.initarray` as a workaround.

**Comment by kawilliams** [comment]
@hkaiser Got everything to work! Thanks to you and the team for your help!

**Pull request merged**
