### PR TITLE
Updating the slicing API

### LINKED ISSUE #295: Python Slicing/Indexing Semantic Mismatch
There is a semantic mismatch between PhySL and Python with regard to subscripting arrays. The following short program demonstrates the problem.

```python
from phylanx.ast import *
import numpy as np

@Phylanx()
def sliceme(a):
    return a[0:1]

a = np.array([1,2,3])
v1 = a[0:1]
v2 = sliceme(a)

print('Python=',type(v1),v1) # Prints an array
print('PhySL=',type(v2),v2) # Prints a value

assert v1[0] == v2[0]
```

The way I think this should work
```
Python Code -> PhySL Code
a[i:j] -> slice(a,[i,j]) -> produce a vector
a[i] -> slice(a, i) -> produce a value
a[i:j:k] -> slice(a,[i,j,k]) -> produce a vector with step size k
a[i:j,n:m] -> slice(a,[i,j],[n,m]) -> produce a matrix
a[i:j,n] -> slice(a,[i,j],n) -> produce a vector
a[n,i:j] -> slice(a,n,[i,j]) -> produce a vector
a[n,m] -> slice(a,n,m) -> produce a value
```

### PR DESCRIPTION
**Pull request by justwagle**
This pull request makes breaking changes to slicing. 
```
Python Code -> PhySL Code
a[i:j] -> slice(a,make_list(i,j)) -> produce a vector
a[i] -> slice(a, i) -> produce a value
a[i:j:k] -> slice(a,make_list(i,j,k)) -> produce a vector with step size k
a[i:j,n:m] -> slice(a,make_list(i,j),make_list(n,m)) -> produce a matrix
a[i:j,n] -> slice(a,make_list(i,j),n) -> produce a vector
a[n,i:j] -> slice(a,n,make_list(i,j)) -> produce a vector
a[n,m] -> slice(a,n,m) -> produce a value
```
This fixes #295.

### CODE REVIEW

**Comment by stevenrbrandt** [comment]
I don't see a branch named "new_slice."

**Comment by stevenrbrandt** [comment]
It seems to not work. Here's my test
```
block(
    define(a,[1,2,3,4]),
    cout(a),
    cout(slice_column(a,[1,3,1])), # expected [2,3], got 2
    cout(slice_column(a,1)) # expected 2, got it.
)
```

**Comment by justwagle** [comment]
@stevenrbrandt You are using the wrong syntax. 
```
block(
      define(a,[1,2,3,4]),
      cout(a),
      cout(slice_column(a,'(1,3,1))), # use '() instead of [ ]
      cout(slice_column(a,1))
)
```

**Comment by hkaiser** [comment]
Alternatively, use `make_list()` instead of `'()`.

**Comment by stevenrbrandt** [comment]
OK, now that I'm using `(), it works. Thanks. LGTM

**Pull request merged**
