### PR TITLE
Adding execution_tree.variable to the Python bindings

### LINKED ISSUE #903: The dtype of a variable is `object`
In the following code:
```py
import numpy as np
from phylanx import Phylanx, PhylanxSession, execution_tree

PhylanxSession.init(1)
	
def variable(value, dtype=None, name=None):
    return execution_tree.var(np.array(value, dtype=dtype))
	
def dtype(x):
	return execution_tree.var(x).dtype
	
@Phylanx
def arange_eager(start, stop, step, dtype):
	return np.arange(start, stop=stop, step=step, dtype=dtype)

def arange(start, stop=None, step=1, dtype='int32'):
	return arange_eager.lazy(start, stop, step, dtype)
	
def test_dtype_1():
	assert dtype(variable(1, dtype='float64')) == 'float64'
	assert dtype(variable(1, dtype='float32')) == 'float32'
	assert dtype(variable(1, dtype='float16')) == 'float16'
test_dtype_1()

def test_dtype_2():
	for dtype in ('int32', 'int64', 'float32', 'float64'):
		t = arange(10, dtype=dtype)
		assert dtype(t) == dtype
test_dtype_2()
```
we get assertion error. If we use another name for the `dtype(x)` as in the below example:
```py
def dt(x):
	return execution_tree.var(x).dtype

def test_dtype_1():
	return dt(variable(1, dtype='float64'))
```
we get this result:
```pytb
object
```

### PR DESCRIPTION
**Pull request by hkaiser**
- remove execution_tree.primitive
- remove execution_tree.var
- flyby: add extract_string_value_strict/is_string_operand_strict

Fixes #903

### CODE REVIEW

**Comment by taless474** [comment]
```py
import numpy as np
from phylanx import Phylanx, PhylanxSession, execution_tree

PhylanxSession.init(1)
	
def variable(value, dtype=None, name=None, constraint=None):
	if constraint is not None:
		raise TypeError("Constraint is the projection function to be "
						"applied to the variable after an optimizer update")
	return execution_tree.variable(np.array(value, dtype=dtype), dtype=dtype, name=name)

def eval(func):
    return func.eval()
	
@Phylanx
def hard_sigmoid_eager(x):
	return hard_sigmoid(x)

def hard_sigmoid(x):
	return hard_sigmoid_eager.lazy(x)
	
def parse_shape_or_val(shape_or_val):
	return shape_or_val, np.random.random(shape_or_val).astype(np.float32) - 0.5

def test_hard_sigmoid_operation(x_shape_or_val):
	x_val = np.random.random(x_shape_or_val).astype(np.float32) - 0.5
	t = hard_sigmoid(variable(x_val))
	return eval(t)

	
print(test_hard_sigmoid_operation((4,2))) 
```
results in:
```pytb
Traceback (most recent call last):
  File "test39.py", line 31, in <module>
    print(test_hard_sigmoid_operation((4,2)))
  File "test39.py", line 28, in test_hard_sigmoid_operation
    return eval(t)
  File "test39.py", line 13, in eval
    return func.eval()
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 450, in eval
    *self.args)
RuntimeError: Unable to cast Python instance of type <class 'phylanx._phylanxd.execution_tree.variable'> to C++ type 'phylanx::execution_tree::primitive_argument_type'
```

**Comment by hkaiser** [comment]
Thanks @taless474, that should be fixed now.

**Comment by taless474** [comment]
Thank you. All the tests pass except for this:
```py
import numpy as np
from phylanx import Phylanx, PhylanxSession, execution_tree

PhylanxSession.init(1)
	
def variable(value, dtype=None, name=None, constraint=None):
	if constraint is not None:
		raise TypeError("Constraint is the projection function to be "
						"applied to the variable after an optimizer update")
	return execution_tree.variable(np.array(value, dtype=dtype), dtype=dtype, name=name)
	

def dtype(x):
	return execution_tree.variable(x).dtype
	
	
def test_dtype_1():
	assert dtype(variable(1, dtype='float64')) == 'float64'
	assert dtype(variable(1, dtype='float32')) == 'float32'
	
print(test_dtype_1())
```
```pytb
Traceback (most recent call last):
  File "test31.py", line 22, in <module>
    print(test_dtype_1())
  File "test31.py", line 19, in test_dtype_1
    assert dtype(variable(1, dtype='float32')) == 'float32'
AssertionError
```
The second assertion fails.

**Comment by hkaiser** [comment]
@taless474 yes, the same fails on CircleCI (https://circleci.com/gh/STEllAR-GROUP/phylanx/24008) :/ 
I'll investigate.

**Comment by hkaiser** [comment]
@taless474 All should be well now.

**Pull request merged**
