### PR TITLE
Fix python prints.

### PR DESCRIPTION
**Pull request by rtohid**

### CODE REVIEW

**Comment by stevenrbrandt** [comment]
This doesn't work. Here's what I get if I run my demo notebook. 
```
d067f
{stack-trace}: 69 frames:
0x7fbbab458242  : ??? + 0x7fbbab458242 in /home/sbrandt/install/hpx/lib/libhpx.so.1
0x7fbbab4558e8  : hpx::termination_handler(int) + 0xd8 in /home/sbrandt/install/hpx/lib/libhpx.so.1
0x7fbbd2965c20  : ??? + 0x7fbbd2965c20 in /lib64/libpthread.so.0
0x7fbbd2c59fee  : PyObject_Call + 0x2e in /lib64/libpython3.5m.so.1.0
0x7fbbd2ce3ce0  : PyEval_CallObjectWithKeywords + 0x30 in /lib64/libpython3.5m.so.1.0
0x7fbbc028c115  : ??? + 0x7fbbc028c115 in /home/sbrandt/.local/lib/python3.5/site-packages/phylanx-0.0.1-py3.5-linux-x86_64.egg/phylanx/_phylanx.cpython-35m-x86_64-linux-gnu.so
0x7fbbc024d983  : ??? + 0x7fbbc024d983 in /home/sbrandt/.local/lib/python3.5/site-packages/phylanx-0.0.1-py3.5-linux-x86_64.egg/phylanx/_phylanx.cpython-35m-x86_64-linux-gnu.so
0x7fbbc026bf74  : ??? + 0x7fbbc026bf74 in /home/sbrandt/.local/lib/python3.5/site-packages/phylanx-0.0.1-py3.5-linux-x86_64.egg/phylanx/_phylanx.cpython-35m-x86_64-linux-gnu.so
0x7fbbc0262106  : ??? + 0x7fbbc0262106 in /home/sbrandt/.local/lib/python3.5/site-packages/phylanx-0.0.1-py3.5-linux-x86_64.egg/phylanx/_phylanx.cpython-35m-x86_64-linux-gnu.so
0x7fbbc025fcb1  : ??? + 0x7fbbc025fcb1 in /home/sbrandt/.local/lib/python3.5/site-packages/phylanx-0.0.1-py3.5-linux-x86_64.egg/phylanx/_phylanx.cpython-35m-x86_64-linux-gnu.so
0x7fbbd2c8ef77  : PyCFunction_Call + 0x77 in /lib64/libpython3.5m.so.1.0
0x7fbbd2ce1194  : PyEval_EvalFrameEx + 0x7394 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cd9170  : PyEval_EvalCodeEx + 0x120 in /lib64/libpython3.5m.so.1.0
0x7fbbd2c6f8f3  : ??? + 0x7fbbd2c6f8f3 in /lib64/libpython3.5m.so.1.0
0x7fbbd2c5a007  : PyObject_Call + 0x47 in /lib64/libpython3.5m.so.1.0
0x7fbbd2c65abe  : ??? + 0x7fbbd2c65abe in /lib64/libpython3.5m.so.1.0
0x7fbbd2c5a007  : PyObject_Call + 0x47 in /lib64/libpython3.5m.so.1.0
0x7fbbd2ca110d  : ??? + 0x7fbbd2ca110d in /lib64/libpython3.5m.so.1.0
0x7fbbd2c5a007  : PyObject_Call + 0x47 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cdebf1  : PyEval_EvalFrameEx + 0x4df1 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cd9170  : PyEval_EvalCodeEx + 0x120 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cd904b  : PyEval_EvalCode + 0x1b in /lib64/libpython3.5m.so.1.0
0x7fbbd2d4e4df  : ??? + 0x7fbbd2d4e4df in /lib64/libpython3.5m.so.1.0
0x7fbbd2c8ef4f  : PyCFunction_Call + 0x4f in /lib64/libpython3.5m.so.1.0
0x7fbbd2cda241  : PyEval_EvalFrameEx + 0x441 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cdef19  : PyEval_EvalFrameEx + 0x5119 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cdef19  : PyEval_EvalFrameEx + 0x5119 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cd9683  : PyEval_EvalCodeEx + 0x633 in /lib64/libpython3.5m.so.1.0
0x7fbbd2c6fadf  : ??? + 0x7fbbd2c6fadf in /lib64/libpython3.5m.so.1.0
0x7fbbd2c5a007  : PyObject_Call + 0x47 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cdc644  : PyEval_EvalFrameEx + 0x2844 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cdfb23  : PyEval_EvalFrameEx + 0x5d23 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cdef19  : PyEval_EvalFrameEx + 0x5119 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cde9a2  : PyEval_EvalFrameEx + 0x4ba2 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cde9a2  : PyEval_EvalFrameEx + 0x4ba2 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cd9683  : PyEval_EvalCodeEx + 0x633 in /lib64/libpython3.5m.so.1.0
0x7fbbd2c6fadf  : ??? + 0x7fbbd2c6fadf in /lib64/libpython3.5m.so.1.0
0x7fbbd2c5a007  : PyObject_Call + 0x47 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cdc644  : PyEval_EvalFrameEx + 0x2844 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cd9683  : PyEval_EvalCodeEx + 0x633 in /lib64/libpython3.5m.so.1.0
0x7fbbd2c6fadf  : ??? + 0x7fbbd2c6fadf in /lib64/libpython3.5m.so.1.0
0x7fbbd2c5a007  : PyObject_Call + 0x47 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cdc644  : PyEval_EvalFrameEx + 0x2844 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cdef19  : PyEval_EvalFrameEx + 0x5119 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cde9a2  : PyEval_EvalFrameEx + 0x4ba2 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cd9170  : PyEval_EvalCodeEx + 0x120 in /lib64/libpython3.5m.so.1.0
0x7fbbd2c6fadf  : ??? + 0x7fbbd2c6fadf in /lib64/libpython3.5m.so.1.0
0x7fbbd2c5a007  : PyObject_Call + 0x47 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cdc644  : PyEval_EvalFrameEx + 0x2844 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cdfb23  : PyEval_EvalFrameEx + 0x5d23 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cde9a2  : PyEval_EvalFrameEx + 0x4ba2 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cdfb23  : PyEval_EvalFrameEx + 0x5d23 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cde9a2  : PyEval_EvalFrameEx + 0x4ba2 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cdef19  : PyEval_EvalFrameEx + 0x5119 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cd9170  : PyEval_EvalCodeEx + 0x120 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cd904b  : PyEval_EvalCode + 0x1b in /lib64/libpython3.5m.so.1.0
0x7fbbd2d4e4df  : ??? + 0x7fbbd2d4e4df in /lib64/libpython3.5m.so.1.0
0x7fbbd2c8ef4f  : PyCFunction_Call + 0x4f in /lib64/libpython3.5m.so.1.0
0x7fbbd2cda241  : PyEval_EvalFrameEx + 0x441 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cdef19  : PyEval_EvalFrameEx + 0x5119 in /lib64/libpython3.5m.so.1.0
0x7fbbd2cd9170  : PyEval_EvalCodeEx + 0x120 in /lib64/libpython3.5m.so.1.0
0x7fbbd2c6f968  : ??? + 0x7fbbd2c6f968 in /lib64/libpython3.5m.so.1.0
0x7fbbd2c5a007  : PyObject_Call + 0x47 in /lib64/libpython3.5m.so.1.0
0x7fbbd2d5ebdd  : ??? + 0x7fbbd2d5ebdd in /lib64/libpython3.5m.so.1.0
0x7fbbd2d5e777  : Py_Main + 0x367 in /lib64/libpython3.5m.so.1.0
0x80c48beb7d    : main + 0xed in /usr/bin/python3
0x7fbbd1ea3731  : __libc_start_main + 0xf1 in /lib64/libc.so.6
0x80c48bec99    : _start + 0x29 in /usr/bin/python3
{what}: Segmentation fault
{config}:
  HPX_WITH_AGAS_DUMP_REFCNT_ENTRIES=OFF
  HPX_WITH_APEX=OFF
  HPX_WITH_ATTACH_DEBUGGER_ON_TEST_FAILURE=OFF
  HPX_WITH_AUTOMATIC_SERIALIZATION_REGISTRATION=ON
  HPX_WITH_CXX14_RETURN_TYPE_DEDUCTION=TRUE
  HPX_WITH_DEPRECATION_WARNINGS=ON
  HPX_WITH_EXECUTION_POLICY_COMPATIBILITY=ON
  HPX_WITH_EXECUTOR_COMPATIBILITY=ON
  HPX_WITH_GOOGLE_PERFTOOLS=OFF
  HPX_WITH_HWLOC=ON
  HPX_WITH_INCLUSIVE_SCAN_COMPATIBILITY=ON
  HPX_WITH_IO_COUNTERS=ON
  HPX_WITH_IO_POOL=ON
  HPX_WITH_ITTNOTIFY=OFF
  HPX_WITH_LOGGING=ON
  HPX_WITH_MORE_THAN_64_THREADS=OFF
  HPX_WITH_NATIVE_TLS=ON
  HPX_WITH_NETWORKING=ON
  HPX_WITH_PAPI=OFF
  HPX_WITH_PARCELPORT_ACTION_COUNTERS=OFF
  HPX_WITH_PARCELPORT_LIBFABRIC=OFF
  HPX_WITH_PARCELPORT_MPI=OFF
  HPX_WITH_PARCELPORT_MPI_MULTITHREADED=OFF
  HPX_WITH_PARCELPORT_TCP=ON
  HPX_WITH_PARCELPORT_VERBS=OFF
  HPX_WITH_PARCEL_COALESCING=ON
  HPX_WITH_PARCEL_PROFILING=OFF
  HPX_WITH_SCHEDULER_LOCAL_STORAGE=OFF
  HPX_WITH_SPINLOCK_DEADLOCK_DETECTION=OFF
  HPX_WITH_STACKTRACES=ON
  HPX_WITH_SWAP_CONTEXT_EMULATION=OFF
  HPX_WITH_THREAD_BACKTRACE_ON_SUSPENSION=OFF
  HPX_WITH_THREAD_CREATION_AND_CLEANUP_RATES=OFF
  HPX_WITH_THREAD_CUMULATIVE_COUNTS=ON
  HPX_WITH_THREAD_DEBUG_INFO=OFF
  HPX_WITH_THREAD_DESCRIPTION_FULL=OFF
  HPX_WITH_THREAD_GUARD_PAGE=ON
  HPX_WITH_THREAD_IDLE_RATES=OFF
  HPX_WITH_THREAD_LOCAL_STORAGE=OFF
  HPX_WITH_THREAD_MANAGER_IDLE_BACKOFF=ON
  HPX_WITH_THREAD_QUEUE_WAITTIME=OFF
  HPX_WITH_THREAD_STACK_MMAP=ON
  HPX_WITH_THREAD_STEALING_COUNTS=ON
  HPX_WITH_THREAD_TARGET_ADDRESS=OFF
  HPX_WITH_TIMER_POOL=ON
  HPX_WITH_TRANSFORM_REDUCE_COMPATIBILITY=ON
  HPX_WITH_TUPLE_RVALUE_SWAP=ON
  HPX_WITH_UNWRAPPED_COMPATIBILITY=ON
  HPX_WITH_VALGRIND=OFF
  HPX_WITH_VERIFY_LOCKS=OFF
  HPX_WITH_VERIFY_LOCKS_BACKTRACE=OFF
  HPX_WITH_VERIFY_LOCKS_GLOBALLY=OFF

  HPX_PARCEL_MAX_CONNECTIONS=512
  HPX_PARCEL_MAX_CONNECTIONS_PER_LOCALITY=4
  HPX_AGAS_LOCAL_CACHE_SIZE=4096
  HPX_HAVE_MALLOC=system
  HPX_PREFIX (configured)=/home/sbrandt/install/hpx
  HPX_PREFIX=/home/sbrandt/install/hpx
{version}: V1.1.0 (AGAS: V3.0), Git: 0867f8aa21
{boost}: V1.65.1
{build-type}: release
{date}: Feb 21 2018 11:13:07
{platform}: linux
{compiler}: GNU C++ version 6.3.1 20161221 (Red Hat 6.3.1-1)
{stdlib}: GNU libstdc++ version 20161221
```

**Comment by rtohid** [comment]
@stevenrbrandt could you please try the master- don't forget to replace `printout` with `print`? It seems Hartmut's latest update on python bindings has fixed this issue and this PR is not needed anymore.

**Comment by hkaiser** [comment]
@rtohid what's the status of this?

**Comment by stevenrbrandt** [comment]
@hkaiser It doesn't work. It dumps core 90% of the time.

**Pull request closed without merging**
