### PR TITLE
Generate newick tree

### PR DESCRIPTION
**Pull request by hkaiser**
This patch proposed to add the following additional facilities:

- Generate Newick tree from execution tree
- Parse primitive names into its parts

This PR is related to #125

### CODE REVIEW

**Comment by hkaiser** [comment]
@kisaacs, @khuck please verify whether the generated tree topology is conforming to your Newick file format readers.

**Comment by hkaiser** [comment]
Here is an example of a generated tree (slightly formatted):
```
(   (   (   (/phylanx/argument#0#filepath/0#7) /phylanx/file_read_csv#0/0#8,
            /phylanx/argument#1#row_start/0#9,
            /phylanx/argument#2#row_stop/0#10,
            /phylanx/argument#3#col_start/0#11,
            /phylanx/argument#4#col_stop/0#12
        ) /phylanx/slice#0/0#13
    ) /phylanx/define-function#0#read_x/0#1,
    /phylanx/function#0#read_x/0#15
) /phylanx/block#0/0#16;
```

where the string used for the tree nodes represent the names of the corresponding primitives (as registered with AGAS). This tree was generated from the following PhySL expression:
```
std::string const read_x_code = R"(block(
    //
    // Read X-data from given CSV file
    //
    define(read_x, filepath, row_start, row_stop, col_start, col_stop,
        slice(file_read_csv(filepath), row_start, row_stop, col_start, col_stop)
    ),
    read_x
))";
```

**Comment by khuck** [comment]
@hkaiser I am not familiar with Newick trees... Kate and I had talked about graphviz trees, which are in "dot" format.  Unless there was a conversation that I don't remember.

**Comment by kisaacs** [comment]
@khuck There are conversion utilities out there since they are both standard formats. (e.g., https://github.com/lindenb/newicktools )  Katy and I will try these soon so we can confirm with Hartmut.

**Comment by hkaiser** [comment]
@kisaacs, @khuck well, if generating dot format would be more appropriate we can certainly change things.

**Comment by kisaacs** [comment]
Here are two standard representations of trees using the sample data, right out of the d3js library. We were able to read it just fine. You may want to verify it is the intended structure.

The one with color is just using color to encode depth. The subtrees can be expanded and collapsed.

indentedexpressiontree
nodelinkexpressiontree

**Comment by hkaiser** [comment]
@kisaacs The structure looks about right. Very nice! Thanks!

**Pull request merged**
