### PR TITLE
Reimplement dictionary type to allow referencing

### LINKED ISSUE #1230: Cannot assign to a dict if the dict is an arg
The code
```
from phylanx import Phylanx

a = {}
@Phylanx
def foo(a):
    a["e"] = 1 #None

foo(a)
```
fails with the message
```
Traceback (most recent call last):
  File "y.py", line 8, in <module>
    foo(a)
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/transducer.py", line 168, in __call__
    result = self.backend.call(*mapped_args, **mapped_kwargs)
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl.py", line 578, in call
    self.wrapped_function.__name__, *args, **kwargs)
RuntimeError: y.py(6, 4): access-argument$a:: storing a value to a local value has no effect: HPX(bad_parameter)
```

### PR DESCRIPTION
**Pull request by hkaiser**
Fixes #1230

### CODE REVIEW

**Comment by hkaiser** [comment]
@stevenrbrandt please verify if this fixes the issue you reported.

**Comment by stevenrbrandt** [comment]
@hkaiser this reverts https://github.com/STEllAR-GROUP/phylanx/pull/1231 so it fails if the assigned value is None instead of 1.

**Comment by stevenrbrandt** [comment]
Or will https://github.com/STEllAR-GROUP/phylanx/pull/1231 be picked up at merge?

**Comment by hkaiser** [comment]
> Or will #1231 be picked up at merge?

Yes, everything will be merged appropriately.

**Comment by stevenrbrandt** [comment]
@hkaiser I'd like to see this deployed.

**Comment by hkaiser** [comment]
@stevenrbrandt this is merged now. Please try whether this fixes your issues or if there are more things that need fixing.

**Pull request merged**
