### PR TITLE
Adding line/column information in case of compilation error

### LINKED ISSUE #226: Can't define arg at the start of a for loop
```
import phylanx
et = phylanx.execution_tree

et.eval("""
block(define(sum, block(
    define(n,0),
    for(store(n,3),n < 10,store(n,n+1),
        block(cout(n))
    ),
    n)), sum)
""")

# However, this should work, too
et.eval("""
block(define(sum, block(
    for(define(n,3),n < 10,store(n,n+1),
        block(cout(n))
    ),
    n)), sum)
""")
```
Output
```
3
4
5
6
7
8
9
RuntimeError: couldn't find given name in symbol table: n: HPX(bad_parameter)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "q.py", line 21, in <module>
    """)
SystemError: <built-in method eval of PyCapsule object at 0x7f13867302d0> returned a result with an error set
```

### LINKED ISSUE #232: physl interpreter error messages
print a line number for execution errors - general enough solution for identifying physl coding errors.

### PR DESCRIPTION
**Pull request by hkaiser**
This fixes #232 
This also fixes #226

### CODE REVIEW

**Comment by hkaiser** [comment]
@ct-clmsn please verify whether this change solves the issue you created.

**Comment by ct-clmsn** [comment]
@hkaiser had a compile time error last night and didn't have time to make fixes. will take another look at it this evening.

**Comment by hkaiser** [comment]
@ct-clmsn yah, I know - sorry for that. I'll commit fixes soon.

**Comment by hkaiser** [comment]
@stevenrbrandt please verify whether this fixes the issue you reported (#226)

**Pull request merged**
