### PR TITLE
Sign primitive returns correct type

### LINKED ISSUE #849: The `sign` primitive returns float instead of int.
```py
from phylanx import Phylanx
import numpy as np

@Phylanx
def do_sign(n):
    return np.sign(n)

print('--')
print(np.sign(2))
print(do_sign(2))
print('--')
print(np.sign(0))
print(do_sign(0))
print('--')
print(np.sign(-2))
print(do_sign(-2))
print('--')
```

output:
```
--
1
1.0
--
0
0.0
--
-1
-1.0
--

```

### PR DESCRIPTION
**Pull request by hkaiser**
Fixes #849

### CODE REVIEW

**Comment by stevenrbrandt** [comment]
I'm surprised that you chose to make this its own primitive rather than allowing the generic mechanism to return integer.

**Comment by hkaiser** [comment]
> I'm surprised that you chose to make this its own primitive rather than allowing the generic mechanism to return integer.

The generic mechanism relies on returning the same type as the argument's type. Extending this would have caused a rewrite of the whole generics primitive. Extracting `sign` was a lot less effort...

**Comment by stevenrbrandt** [comment]
@hkaiser I don't think this should be its own primitive. I think it should be another kind of generic primitive, one that doesn't automatically upcast all results to be doubles. If you do that, then np.square() should also move here--and possibly other primitives.

**Comment by hkaiser** [comment]
@stevenrbrandt better now?

**Comment by stevenrbrandt** [comment]
@hkaiser it is better, but there is no test of the new functionality.

**Comment by stevenrbrandt** [comment]
@hkaiser want me to add a test?

**Comment by hkaiser** [comment]
> want me to add a test?

I already added some (here: https://github.com/STEllAR-GROUP/phylanx/pull/860/files#diff-027e33a92665bf61eab6668eb58bcd47R755), but please feel free to add more.

**Comment by stevenrbrandt** [comment]
@hkaiser OK, I see them now. Those seem good.

**Pull request merged**
