### PR TITLE
Adding arithmetic operations to execution_tree.variable

### PR DESCRIPTION
**Pull request by hkaiser**
This add the basic arithmetic operations to `variable` (add, sub, mul, div, neg, assign-add, assign-sub)

### CODE REVIEW

**Comment by taless474** [comment]
I tried this:
```py
import numpy as np
from numpy.testing import assert_allclose
from phylanx import Phylanx, PhylanxSession, execution_tree

PhylanxSession.init(1)

def variable(value, dtype=None, name=None, constraint=None):
	if dtype is None:
		dtype = "float32"
	elif dtype not in ["float16","float32","float64","int16","int32","int64","bool"]:
		raise TypeError("unsupported dtype")
	if constraint is not None:
		raise TypeError("Constraint is the projection function to be "
						"applied to the variable after an optimizer update")
	from phylanx.ast.physl import PhySL
	if isinstance(value, PhySL.eval_wrapper):
		return execution_tree.variable(value.code(), dtype)
	if isinstance(value, execution_tree.variable):
		return value
	return execution_tree.variable(value, dtype=dtype, name=name)
	
def eval(func):
    return func.eval()
	
@Phylanx
def update_add_eager(x, increment):
	return add(x, increment)

def update_add(x, increment):
	return update_add_eager.lazy(x, increment)
	
def test_update_add():
	x = np.random.randn(3, 4)
	x_var = variable(x)
	increment = np.random.randn(3, 4)

	x += increment
	# print(eval(update_add(x_var, increment)))
	# print(x) # equal to the result of the above line
	# print(eval(x_var))

	assert_allclose(x, eval(x_var), atol=1e-05)
	
test_update_add()
```
which resulted in:
```pytb
Traceback (most recent call last):
  File "test59.py", line 44, in <module>
    test_update_add()
  File "test59.py", line 42, in test_update_add
    assert_allclose(x, eval(x_var), atol=1e-05)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\numpy\testing\_private\utils.py", line 1452, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\numpy\testing\_private\utils.py", line 789, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-07, atol=1e-05

(mismatch 100.0%)
 x: array([-2.26454 ,  1.108113, -1.036032,  0.4514  ,  1.100956, -1.067621,
       -0.402638,  0.951161, -1.449791, -1.108185,  0.492278, -0.188493])
 y: array([-1.792305,  0.110852, -0.222915,  0.382778,  0.958932, -1.641614,
        0.282282,  0.246248, -0.289201, -0.00992 ,  0.798759, -0.401575])
```

**Comment by hkaiser** [comment]
@taless474 the first example above has to fail as you essentially do this:
```
x = np.random.randn(3, 4)
x_var = variable(x)
increment = np.random.randn(3, 4)
x += increment
assert x == x_var
```
which should fail (except if the increment is zero across the board.

What are you trying to achieve?

**Comment by taless474** [comment]
Sorry, I forgot to uncomment `eval(update_add(x_var, increment))`

**Comment by hkaiser** [comment]
@taless474 try writing this as:
```
def test_update_add():
	x = np.random.randn(3, 4)
	x_var = variable(x)
	increment = np.random.randn(3, 4)

	x += increment
	x_var += increment

	assert_allclose(x, eval(x_var), atol=1e-05)
```
that should work. This PR directly implements the necessary logic in the backend so you can directly manipulate variables.

**Comment by taless474** [comment]
Got it. This works, thanks.
```py
import numpy as np
from numpy.testing import assert_allclose
from phylanx import Phylanx, PhylanxSession, execution_tree

PhylanxSession.init(1)

def variable(value, dtype=None, name=None, constraint=None):
	if dtype is None:
		dtype = "float32"
	elif dtype not in ["float16","float32","float64","int16","int32","int64","bool"]:
		raise TypeError("unsupported dtype")
	if constraint is not None:
		raise TypeError("Constraint is the projection function to be "
						"applied to the variable after an optimizer update")
	from phylanx.ast.physl import PhySL
	if isinstance(value, PhySL.eval_wrapper):
		return execution_tree.variable(value.code(), dtype)
	if isinstance(value, execution_tree.variable):
		return value
	return execution_tree.variable(value, dtype=dtype, name=name)
	
def eval(func):
    return func.eval()

def update_add(x, increment):
	x += increment
	return x
	
def test_update_add():
	x = np.random.randn(3, 4)
	x_var = variable(x)
	increment = np.random.randn(3, 4)

	x += increment
	eval(update_add(x_var, increment))

	assert_allclose(x, eval(x_var), atol=1e-05)
	
test_update_add()
```

**Pull request merged**
