### PR TITLE
Enable building external Phylanx executables

### LINKED ISSUE #304: CMake Issues with External Builds
I am trying to build a Phylanx application in an external directory using CMake. My CMakeLists.txt contains the following:
```
cmake_minimum_required (VERSION 2.6)
project (phylanx_test)
find_package (Phylanx)
add_executable (phylanx_test phylanx_test.cpp)
Phylanx_setup_target(phylanx_test)
```
I am getting the following error:

CMake Error at C:/Users/adria/Git/phylanx/build-master/lib/cmake/Phylanx/PhylanxMacros.cmake:74 (include):
  include could not find load file:

    PHYLANX_SetupAllocator
Call Stack (most recent call first):
  C:/Users/adria/Git/phylanx/build-master/lib/cmake/Phylanx/PhylanxConfig.cmake:57 (phylanx_setup_allocator)
  CMakeLists.txt:11 (find_package)

CMake Error at C:/Users/adria/Git/phylanx/cmake/Phylanx_SetupTarget.cmake:154 (hpx_handle_component_dependencies):
  Unknown CMake command "hpx_handle_component_dependencies".
Call Stack (most recent call first):
  CMakeLists.txt:23 (Phylanx_setup_target)

I am using Phylanx top of Master.
Any help would be appreciated!

### PR DESCRIPTION
**Pull request by hkaiser**
- moving all preprocessor configuration definitions from the command line
  to a separate file defines.hpp
- fixing existing problems
- adding example demonstrating the use of the Phylanx external build system

This fixes #304

### CODE REVIEW

**Comment by aserio** [comment]
I defined HPX_DIR, Phylanx_DIR, CMAKE_BUILD_TYPE=Debug, and CMAKE_TOOLCHAIN (vcpkg) and hit this error:
```
CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/FindBLAS.cmake:699 (message):
  A required library with BLAS API not found.  Please specify library
  location.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindLAPACK.cmake:162 (find_package)
  cmake/Phylanx_SetupBlaze.cmake:8 (find_package)
  CMakeLists.txt:126 (phylanx_setup_blaze)
```
I will try to dig further into this tomorrow.

**Comment by hkaiser** [comment]
For me setting `Phylanx_DIR` was sufficient. HPX etc. will be transitively found (at least that's the idea).

**Comment by stevenrbrandt** [comment]
Are you doing ```apt-get install -y libblas-dev liblapack-dev```? I did this on my docker image.

**Comment by khuck** [comment]
@aserio What @stevenrbrandt said.  If your BLAS/LAPACK libraries aren't in the "default" system location, you have to set LAPACK_DIR, BLAS_DIR, LAPACK_ROOT and BLAS_ROOT before configuring Blaze.  On one of the Buildbot servers, I also have to pass this to the Blaze configuration:

```bash
-DBLAS_LIBRARIES=${BLAS_DIR}/lib64/libblas.so -DLAPACK_LIBRARIES=${LAPACK_DIR}/lib64/liblapack.so
```

See http://ktau.nic.uoregon.edu:8020/builders/ppc64le-clang5-release/builds/340/steps/Get%20and%20Configure%20Blaze/logs/stdio for an example of a Cmake line that requires all that nonsense in order to work.

**Comment by aserio** [comment]
After looking deeper into this today, @hkaiser and I believe I was running into this error because my CMake minimum version was set to version 2.6. After updating the minimum version to 3.3.2 this change set worked as advertised.

**Pull request merged**
