### PR TITLE
add sequential gauss inverse plugin

### PR DESCRIPTION
**Pull request by rhecto1**
attempt to add sequential gauss inverse plugin for matrix inverse using gaussian elimination.

### CODE REVIEW

**Comment by hkaiser** [comment]
@rhecto1 I have rebased your branch on master. Could you please fix the compilation errors on the CircleCI builder?

**Comment by rhecto1** [comment]
> @rhecto1 I have rebased your branch on master. Could you please fix the compilation errors on the CircleCI builder?

Yes, I'll change that ASAP, though I'm not sure why it works on my computer but std::swap fails here.

**Comment by hkaiser** [comment]
> @rhecto1 I have rebased your branch on master. Could you please fix the compilation errors on the CircleCI builder?
> 
> Yes, I'll change that ASAP, though I'm not sure why it works on my computer but std::swap fails here.

From what I can see, your code tries to swap rvalues. The Microsoft compiler has an infamous bug that let's you do that despite that it is illegal C++. I also think, that it was not doing the thing you expected even if this was compiling.

**Comment by hkaiser** [comment]
> @rhecto1 I have rebased your branch on master. Could you please fix the compilation errors on the CircleCI builder?
> Yes, I'll change that ASAP, though I'm not sure why it works on my computer but std::swap fails here.
> 
> From what I can see, your code tries to swap rvalues. The Microsoft compiler has an infamous bug that let's you do that despite that it is illegal C++. I also think, that it was not doing the thing you expected even if this was compiling.

Actually, adding an `#include <phylanx/util/detail/bad_swap.hpp>` might solve the issue (see: https://github.com/STEllAR-GROUP/phylanx/blob/master/phylanx/util/detail/bad_swap.hpp)

**Pull request merged**
