### PR TITLE
Update Phylanx Python Package

### PR DESCRIPTION
**Pull request by rtohid**
* Restructure Python package.
    - move transformation functionalities to module transformation under ast.
    - move AST utility functions to utilities under ast.

* Change the phyfun class to PhyTransformer and refactor the implementation to avoid elifs when possible.

### CODE REVIEW

**Comment by stevenrbrandt** [comment]
I've looked over the code for a while and everything seems fine. Is this supposed to be able to generate something other than PhySL, @rtohid ? I seem to recall that you said so at the meeting.

**Comment by rtohid** [comment]
Thank you @stevenrbrandt .
Now you can pass the target to the Phylanx decorator- please see the last commit I just added.

**Comment by stevenrbrandt** [comment]
This code breaks the test suite in a few important ways. Still trying to figure it out.

**Comment by rtohid** [comment]
Type of the decorated function is converted to the decorator if the decorator does not take any arguments, otherwise, it remains a function. We can make a change so, optionally, the PhySL code is also returned- not as an attribute. @stevenrbrandt Please let me know if you can think of a better way. Thank you.

**Comment by stevenrbrandt** [comment]
I added another simple test to eval.py which, surprisingly, breaks things. Apparently, (1) we need more tests and (2) some things got lost in the refactoring.

**Comment by hkaiser** [comment]
@rtohid  Is this ready to move forward now?

**Comment by stevenrbrandt** [comment]
OK, I approve this pull request. @hkaiser ? What say you?

**Comment by hkaiser** [comment]
@stevenrbrandt If you are happy - I'm happy too!

**Comment by rtohid** [comment]
@hkaiser. If tests pass LGTM.

**Pull request merged**
